# Server settings (ServerProperties)
server:
  port: 8081
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30
  use-forward-headers: true
spring:
    datasource:
        name: base
        url: jdbc:mysql://127.0.0.1:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 1qazCDE#5tgb
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        #启动执行sql
        schema: classpath:init.sql
        data: classpath:update.sql
        sql-script-encoding: utf-8
    thymeleaf:
        # Enable template caching.
        cache: false
        # Check that the templates location exists.
        check: template-location=true
        # Content-Type value.
        scontent-type: text/html
        # Enable MVC Thymeleaf view resolution.
        enabled: true
        # Template encoding.
        encoding: UTF-8
        # Comma-separated list of view names that should be excluded from resolution.
        excluded-view-names:
        # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
        mode: HTML5
        # Prefix that gets prepended to view names when building a URL.
        prefix: classpath:/templates/
        # Suffix that gets appended to view names when building a URL.
        suffix: .html
        # Order of the template resolver in the chain. spring.thymeleaf.view-names= # Comma-separated list of view names that can be resolved.
        template-resolver-order:
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 5000
        pool:
            max-idle: 20
            min-idle: 1
            max-active: 20
            max-wait: -1
        database: 0
mybatis:
    mapperLocations: classpath:mybatis_mapper/*.xml
    typeAliasesPackage: classpath:model
    sqlImpl: log4j2

