# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (1, 1, '用户管理', null, '0/', 'userInfo:view', 'menu', 'userInfo/userList');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (2, 1, '用户添加', 1, '0/1', 'userInfo:add', 'button', 'userInfo/userAdd');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (3, 1, '用户删除', 1, '0/1', 'userInfo:del', 'button', 'userInfo/userDel');
# INSERT INTO sys_role(id, available, description, role) VALUES (1, 1, '管理员', 'admin');
# INSERT INTO sys_role(id, available, description, role) VALUES (2, 1, 'VIP会员', 'vip');
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 1);
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 2);
# INSERT INTO user_info (id,username,name,password,salt,status) VALUES (1, 'admin', '管理员', 'd3c59d25033dbf980d29554025c23a75', '8d78869f470951332959580424d4bf4f', 0);
# INSERT INTO sys_user_role(user_id, role_id) VALUES (1, 1);
# INSERT INTO sys_user_role(user_id, role_id) VALUES (1, 2);
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (1,'/logout','logout,kickout',1,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (2,'/index','user,kickout',2,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (3,'/','user,kickout',3,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (4,'/**','anon,kickout',4,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (5,'/kickout','anon',5,now());
# INSERT INTO web_category(id, name, parent_id, create_time) VALUE (1, '测试类别', null, now());
# INSERT INTO web_category(id, name, parent_id, create_time) VALUE (2, '测试类别2', 1, now());
# insert into web_page(id,title,page,create_time)VALUES(1,'公司','company',now());
# insert into web_page(id,title,page,create_time)VALUES(2,'团队','team',now());
# insert into web_page(id,title,page,create_time)VALUES(3,'招聘','careers',now());
# insert into web_page(id,title,page,create_time)VALUES(4,'企业历程','course',now());
# insert into web_page(id,title,page,create_time)VALUES(5,'企业文化','culture',now());
# insert into web_image(id,name,link,position,address,create_time)VALUES(1,"案例详情.jpg",null,'header_1','案例详情.jpg',now());
# insert into web_image(id,name,link,position,address,create_time)VALUES(2,"招聘页.jpg",null,'center_1','招聘页.jpg',now());
# insert into web_page_image VALUES (1,1);
# insert into web_page_image VALUES (1,2);
# insert into web_page_image VALUES (2,1);
# insert into web_page_image VALUES (2,2);
# insert into web_html(id,html,position)VALUES(1,'<p>公司页左侧</p>','left');
# insert into web_html(id,html,position)VALUES(2,'<p>公司页右侧</p>','right');
# insert into web_html(id,html,position)VALUES(3,'<p>团队页左侧</p>','left');
# insert into web_html(id,html,position)VALUES(4,'<p>团队页右侧</p>','right');
# insert into web_html(id,html,position)VALUES(5,'<p>招聘内容：岗位 java开发</p>',null);
# insert into web_html(id,html,position)VALUES(6,'<p>企业历程</p>',null);
# insert into web_html(id,html,position)VALUES(7,'<p>企业文化</p>',null);
# insert into web_page_html VALUES (1,1);
# insert into web_page_html VALUES (1,2);
# insert into web_page_html VALUES (2,3);
# insert into web_page_html VALUES (2,4);
# insert into web_page_html VALUES (3,5);
# insert into web_page_html VALUES (4,6);
# insert into web_page_html VALUES (5,7);
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (4, 1, '产品管理', null, '0/', 'product:view', 'menu', 'userInfo/userList');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (5, 1, '产品添加', 1, '0/1', 'product:add', 'button', 'userInfo/userAdd');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (6, 1, '产品删除', 1, '0/1', 'product:del', 'button', 'userInfo/userDel');
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 4);
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 5);
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 6);
# INSERT INTO web_info (id,name,title,open_time,introduction,address,phone,email,fax,url,icp,map)VALUES (1,"一尚红文化创意有限公司","一心一意 尚德尚品","","简介","浙江省杭州市拱墅区金通国际大厦1-1幢2单元1405室","86-0571-86016510","86-0571-86016510","291677644@qq.com","www.ysh33.com","","");
# INSERT INTO web_category(id,name,content,parent_id,icon,create_time)values(1,'服务项目','',null,null,now());
# INSERT INTO web_category(id,name,content,parent_id,icon,create_time)values(2,'会议资源','',null,null,now());
# INSERT INTO web_category(id,name,content,parent_id,icon,create_time)values(3,'类别2','',1,null,now());
insert into aj_banner(id, img_name, link, path, create_time) values (1, "banner_1.png", "", "banner_1.png", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (1, "安监类别", "", "", "安监类别", null, "", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (2, "危险化学品", "icon_wx.png", "icon_wx.png", "危险化学品是一种xxx", 1, "weixianhuaxuepin", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (3, "建筑施工", "icon_jz.png", "icon_jz.png", "建筑施工是一种xxx", 1, "jianzhushigong", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (4, "人员密集场所", "icon_ry.png", "icon_ry.png", "人员密集场所是一种xxx", 1, "renyuanmijichangsuo", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (5, "交通运输", "icon_jt.png", "icon_jt.png", "交通运输是一种xxx", 1, "jiaotongyunshu", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (6, "工业企业", "icon_gy.png", "icon_gy.png", "工业企业是一种xxx", 1, "gongyeqiye", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (7, "消防", "icon_xf.png", "icon_xf.png", "消防是一种xxx", 1, "xiaofang", now());
insert into aj_category(id, category_name, icon, icon_name, introduction, parent_id, json_name, create_time) values (8, "特种设备", "icon_tz.png", "icon_tz.png", "特种设备是一种xxx", 1, "tezhongshebei", now());
insert into aj_course(id, aj_type, content, course_name, course_type, home_page, icon, icon_name, create_time, update_time) values (1, "危险化学品", "XXXXXX", "课程1", 1, true, "1.png", "1.png", now(), now());
insert into aj_exam(id, exam_name, exam_type, introduction, standard, start_date, end_date, exam_duration, role, create_time, update_time) values (1, "考试1", "综合测验", "本次考试是为了考察", 6, now(), now(), 30, "{'ajType':{'消防安全':3,'交通运输':10},'questionType':{'trueFalse':5,'simpleChoice':6,'multipleChoice':2},'difficulty':{'1':2,'2':10,'4':1}}", now(), now());
insert into aj_question_tf(id, question, question_type, difficulty, aj_type, analysis, answer, create_time, update_time) values (1, "问题XXX,此说法是否正确", "tf", 1, "危险化学品", "这题为啥会是", "正确", now(), now());
insert into aj_question_sc(id, question, question_type, difficulty, aj_type, analysis, answer, choice_a, choice_b, choice_c, choice_d, create_time, update_time) values (1, "问题XXX,下列哪个说法正确", "sc", 2, "消防", "这题为啥会是", "choiceA", "答案a", "答案b", "答案c", "答案d", now(), now());
insert into aj_question_mc(id, question, question_type, difficulty, aj_type, analysis, answer, choice_a, choice_b, choice_c, choice_d, create_time, update_time) values (1, "问题XXX,下列哪几个说法正确", "mc", 3, "消防", "这题为啥会是", "choiceA,choiceB", "答案a", "答案b", "答案c", "答案d", now(), now());
insert into aj_news(id, title, introduction, content, news_time, create_time) values (1, "新闻标题", "新闻简介", "新闻内容", now(), now());
insert into aj_course_tf(course_id, question_id) values(1,1);
insert into aj_course_sc(course_id, question_id) values(1,1);
insert into aj_course_mc(course_id, question_id) values(1,1);