# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (1, 1, '用户管理', null, '0/', 'userInfo:view', 'menu', 'userInfo/userList');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (2, 1, '用户添加', 1, '0/1', 'userInfo:add', 'button', 'userInfo/userAdd');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (3, 1, '用户删除', 1, '0/1', 'userInfo:del', 'button', 'userInfo/userDel');
# INSERT INTO sys_role(id, available, description, role) VALUES (1, 1, '管理员', 'admin');
# INSERT INTO sys_role(id, available, description, role) VALUES (2, 1, 'VIP会员', 'vip');
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 1);
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 2);
# INSERT INTO user_info (id,username,name,password,salt,status) VALUES (1, 'admin', '管理员', 'd3c59d25033dbf980d29554025c23a75', '8d78869f470951332959580424d4bf4f', 0);
# INSERT INTO sys_user_role(user_id, role_id) VALUES (1, 1);
# INSERT INTO sys_user_role(user_id, role_id) VALUES (1, 2);
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (1,'/logout','logout,kickout',1,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (2,'/index','user,kickout',2,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (3,'/','user,kickout',3,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (4,'/**','anon,kickout',4,now());
# INSERT INTO sys_permission_init(id, url, permission_init, sort, create_time) VALUES (5,'/kickout','anon',5,now());
# INSERT INTO web_catagory(id, name, parent_id, create_time) VALUE (1, '测试类别', null, now());
# INSERT INTO web_catagory(id, name, parent_id, create_time) VALUE (2, '测试类别2', 1, now());
# insert into web_page(id,title,page,create_time)VALUES(1,'公司','company',now());
# insert into web_page(id,title,page,create_time)VALUES(2,'团队','team',now());
# insert into web_page(id,title,page,create_time)VALUES(3,'招聘','careers',now());
# insert into web_image(id,name,link,position,address,create_time)VALUES(1,"案例详情.jpg",null,'header_1','案例详情.jpg',now());
# insert into web_image(id,name,link,position,address,create_time)VALUES(2,"招聘页.jpg",null,'center_1','招聘页.jpg',now());
# insert into web_page_image VALUES (1,1);
# insert into web_page_image VALUES (1,2);
# insert into web_page_image VALUES (2,1);
# insert into web_page_image VALUES (2,2);
# insert into web_html(id,html,position)VALUES(1,'<p>公司页左侧</p>','left');
# insert into web_html(id,html,position)VALUES(2,'<p>公司页右侧</p>','right');
# insert into web_html(id,html,position)VALUES(3,'<p>团队页左侧</p>','left');
# insert into web_html(id,html,position)VALUES(4,'<p>团队页右侧</p>','right');
# insert into web_html(id,html,position)VALUES(5,'<p>招聘内容：岗位 java开发</p>',null);
# insert into web_page_html VALUES (1,1);
# insert into web_page_html VALUES (1,2);
# insert into web_page_html VALUES (2,3);
# insert into web_page_html VALUES (2,4);
# insert into web_page_html VALUES (3,5);
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (4, 1, '产品管理', null, '0/', 'product:view', 'menu', 'userInfo/userList');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (5, 1, '产品添加', 1, '0/1', 'product:add', 'button', 'userInfo/userAdd');
# INSERT INTO sys_permission(id,available,name,parent_id,parent_ids,permission,resource_type,url) VALUES (6, 1, '产品删除', 1, '0/1', 'product:del', 'button', 'userInfo/userDel');
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 4);
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 5);
# INSERT INTO sys_role_permission(role_id, permission_id) VALUES (1, 6);
# INSERT INTO web_info (id,name,title,open_time,introduction,address,phone,email,fax,url,icp,map)VALUES (1,"一尚红文化创意有限公司","一心一意 尚德尚品","","{'公司类别':'杭州一尚红文化创意有限公司是一家专业为企业、产品、活动提供品牌营销、公关策划及全方位服务的文化创意产业实体。','公司宗旨':'公司自2009年成立以来，一直秉承“一心一意、尚德尚品”的服务宗旨，始终坚持以品质求生存，以创新求发展，以服务为根本的经营理念，致力于企业品牌设计、营销策划、广告宣传、商业路演及大型活动策划，全力帮助客户聚焦品牌价值,创造卓越品牌。','公司展望':'目前，一尚红的客户遍及多个行业，已为诸多知名的企业及机构提供品牌咨询、设计服务和制作执行，涵盖金融、通讯、互联网、房地产、旅游、酒店、餐饮、服饰、传媒、娱乐、教育等行业，其中西博会、G20峰会会务服务，智能机器人全球峰会等诸多成功案例。完善的服务和卓越的品质普获客户的认同。'}","浙江省杭州市拱墅区金通国际大厦1-1幢2单元1405室","86-0571-86016510","86-0571-86016510","291677644@qq.com","www.ysh33.com","","");
# INSERT INTO web_catagory(id,name,content,parent_id,icon,create_time)values(1,'服务项目','',null,null,now());
# INSERT INTO web_catagory(id,name,content,parent_id,icon,create_time)values(2,'会议资源','',null,null,now());
# INSERT INTO web_catagory(id,name,content,parent_id,icon,create_time)values(3,'类别2','',1,null,now());